Add controllers
Notapie/java-shareit pull request #1
Opened 2023-09-28 12:15 UTC by Notapie

2023-09-28 16:30 UTC, EugeneLenkevich requested changes
Привет, Илья! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-28 16:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/advice/ErrorController.java
> +        log.debug(e.getMessage());
log.debug

Так уж не debug уж уровень логирования, это же сообщение об ошибке :D

2023-09-28 16:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceInMemoryImpl.java
> +        return searchResult.values();
А не проще складывать в Set :)
Иди есть еще второй вариант, со стримом 

```
return idToItem.values().stream()
.filter (item ->  item.getName().toLowerCase()...  )
.distinct()
.collect(toList());
```

И, кстати, а если name или description вдруг окажется null то мы получим ошибку :)

2023-09-28 16:30 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.debug("Create user request. " + userRequestDto);
Мне кажется что тут стоит разобраться мы хотим залогировать: если мы хотим залогировать сами бизнес-операции, то стоит перенести логирование на уровень сервиса, так как это его обязанности (допустим метод сервиса вызвал не контроллер, а задача по расписанию, тогда вызов залогирован тогда не будет), а вот если хотим залогировать http-запросы, то тут есть пара моментов а) эти данные могут сильно забивать логи, потому лучше сделать уровень логированитя - log.debug(...) для них. Далее, если нам надо именно http-запросы, то данных в таком логе недостаточно, в запросе как минимум есть еще заголовки и пр
То есть, надо разобраться что именно мы тут хотим логировать и принять соответствующее решение, иначе просто логи неинформативные будут :)

PS
для логирования http-запросов можешь вот это попробовать, если желание будет
https://github.com/zalando/logbook
как непосредственно прикрутить
https://errorsfixing.com/how-to-instantiate-logbook-in-spring-boot-app/

2023-10-02 00:06 UTC, Notapie commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceInMemoryImpl.java
> +        return searchResult.values();
Там даже лист подойдёт, мы ведь только один раз проходимся по вещам)

2023-10-02 00:08 UTC, Notapie commented on src/main/java/ru/practicum/shareit/advice/ErrorController.java
> +        log.debug(e.getMessage());
Ну, я рассуждал так, что эти ошибки как бы "штатные" и в обычном логе они не нужны. Только для дебага могут пригодиться)

2023-10-02 00:12 UTC, Notapie commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceInMemoryImpl.java
> +        return searchResult.values();
Честно говоря, мне почему-то не нравится использовать стримы. Мне кажется, что эти стримы не очень производительны. Скорее всего ошибаюсь, просто не смог собрать достаточно информации про их реализацию

2023-10-02 00:13 UTC, Notapie commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        log.debug("Create user request. " + userRequestDto);
Полностью согласен, не туда полез)

2023-10-02 00:13 UTC, Notapie commented on src/main/java/ru/practicum/shareit/advice/ErrorController.java
> +        log.debug(e.getMessage());
В любом случае, поправил этот момент)

2023-10-02 00:20 UTC, Notapie commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceInMemoryImpl.java
> +        return searchResult.values();
Но исходя из того, как они используются в коде, мне всё-таки кажется, что да, они неэффективны. Лаконичны, но неэффективны

2023-10-02 04:44 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceInMemoryImpl.java
> +        return searchResult.values();
Ну все верно, у них есть свой оверхед. Но тут такой момент - код бывает читаемый(= легкий в поддержке, то есть дешевый в эксплуатации), а бывает производительный(часто его вообще без бутылки не разобрать и тем более так просто баги не поправить). Мы должны всегда искать баланс между производительностью и поддерживаемостью кода. Хотя, оверхед от стримов копеешный на фоне влияния других факторов, чаще всего основную нагрузку дает ввод-вывод, то есть сеть и обращение к БД
В общем и в целом да, тут кругом компромисы :)

2023-10-02 04:47 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-10-02 06:17 UTC, merged