Add bookings
Notapie/java-shareit pull request #2
Opened 2023-10-19 11:17 UTC by Notapie

2023-10-19 16:52 UTC, EugeneLenkevich requested changes
Привет, Илья! Спасибо за PR.

Отличная работа! :)
Я отметил пару моментов про методы репозитория, хотелось бы его причесать, сделать более удобным :)

2023-10-19 16:52 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    List<Booking> findBookingsByBooker_IdAndStartTimeIsBeforeAndEndTimeIsAfterOrderByStartTimeDesc(int bookerId, LocalDateTime firstDate, LocalDateTime secondDate);
findBookingsByBooker_IdAndStartTimeIsBeforeAndEndTimeIsAfterOrderByStartTimeDesc

В подобном случае, когда имя метода получается таким длинным то наверно стоит написать пуками запрос и указать его в @Query. В таким случае мы метод можем назвать сильно короче, подобные длиннюще методы неудобны, можно легко ошибиться :)

2023-10-19 16:52 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    @Query("from Booking where item.id = ?1 and status = 'APPROVED' and startTime <= ?2 order by startTime desc")
?1

Все таки лучше использовать плейсхолдеры, их и читать проще и надежней, если что то добавить новых параметров в метод а запросы не обновить

from Booking where item.id = :itemId and status = 'APPROVED' and startTime <= currentTime order by startTime desc

и еще

order by startTime desc

Ну и раз тут Pageable то в запросе не надо сортировку задавать, сортировка есть в Pageable

2023-10-28 17:59 UTC, Notapie commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    List<Booking> findBookingsByBooker_IdAndStartTimeIsBeforeAndEndTimeIsAfterOrderByStartTimeDesc(int bookerId, LocalDateTime firstDate, LocalDateTime secondDate);
Исправил)

2023-10-28 18:02 UTC, Notapie commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    List<Booking> findBookingsByBooker_IdAndStartTimeIsBeforeAndEndTimeIsAfterOrderByStartTimeDesc(int bookerId, LocalDateTime firstDate, LocalDateTime secondDate);
Очень хотел ещё поинтересоваться, есть ли возможность написать на jpql вот те два единственных запроса, которые сейчас на native sql написаны? Я сходу написал эти запросы на нативе, а вот на jpql я голову за несколько ночей разбил об стол пока пытался что-то придумать

2023-10-28 18:03 UTC, Notapie commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    @Query("from Booking where item.id = ?1 and status = 'APPROVED' and startTime <= ?2 order by startTime desc")
Исправил, но мне не очень нравится это решение, потому что мне пришлось там же при вызове указывать название столбца сортировки, мне кажется, что будет не совсем очевидно потом, при изменении названия столбца его искать

2023-10-28 18:13 UTC, Notapie commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    List<Booking> findBookingsByBooker_IdAndStartTimeIsBeforeAndEndTimeIsAfterOrderByStartTimeDesc(int bookerId, LocalDateTime firstDate, LocalDateTime secondDate);
`@Query(value = "SELECT DISTINCT ON (item_id) * FROM \"booking\" WHERE item_id IN ?1 AND status = 'APPROVED' AND start_time <= ?2 ORDER BY item_id, start_time DESC", nativeQuery = true)`

2023-10-28 18:19 UTC, Notapie commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    @Query("from Booking where item.id = ?1 and status = 'APPROVED' and startTime <= ?2 order by startTime desc")
Вообще мне там нужно только одна строка из этих запросов, а возможности установить limit 1 в jpql нельзя. Есть ли возможность как-то более элегантно такой запрос организовать?

2023-10-28 18:21 UTC, Notapie commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    @Query("from Booking where item.id = ?1 and status = 'APPROVED' and startTime <= ?2 order by startTime desc")
Я поэтому и прибегнул к pageable, хотя в истинном определении он там не нужен, там просто можно указать size 1, но это выглядит костыльненько

2023-10-29 03:50 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    List<Booking> findBookingsByBooker_IdAndStartTimeIsBeforeAndEndTimeIsAfterOrderByStartTimeDesc(int bookerId, LocalDateTime firstDate, LocalDateTime secondDate);
Да вроде как примерно так же запрос на jpql и будет выглядеть 

select distinct b from booking b where b.item.id in (:itemId) and status = 'APPROVED' and startTime<=:startTime order by b.item.id and b.startTime desc

Единственное реальный запрос с джионами получится

2023-10-29 03:56 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingJpaRepository.java
> +    @Query("from Booking where item.id = ?1 and status = 'APPROVED' and startTime <= ?2 order by startTime desc")
Ну на самом деле Pageable как раз и является стандартным путем задания задания limit, ну и сортировки заодно :)
Только проходить его будем вроде как на следующем задании

Но, я тебя понял, иначе более хитрый  запрос получается для поиска максимума :)

2023-10-29 04:04 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-10-31 21:18 UTC, merged